services:
  db:
    image: postgres
    env_file:
      - ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d nexustms"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: