services:
  db:
    image: postgres
    env_file:
      - ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: .
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ".env"
    ports:
      - "8080:8080"

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge